### ISSUE TITLE
React Starter should have more tests

### ISSUE THREAD

**Issue by bewatts** [pivotal-cf/react-starter#10]
Many components are missing tests.  Given that this exists as a framework for many Pivotal projects, having documentation on why and how things are laid out would be helpful.

**Comment by charleshansen** [comment]
The goal was to have tests for each type of thing. I suppose I should just put in tests for everything. 

Actually documenting everything is a long task, do you have specific parts that were confusing? I can start with documenting which tests are supposed to demonstrate what. PRs welcome if you figure out something and wish it was in there.
