### ISSUE TITLE
spec-integration task sometimes builds assets without styles

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/react-starter#11]
We're having an issues when we run `gulp` (with the default task) which calls the `spec-integration` job. For some reason it doesn't build with any stylesheets.

However, when running `gulp spec-integration` by itself it builds with the css fine.

Looking at the generated `public/config.js` we can see that`gulp` gives us:

```
window.AppName = {
  config: {
    "globalNamespace": "AppName",
    "scripts": ["application.js"],
    "stylesheets": [],
    "useRevManifest": false,
    "hotModule": true,
    "useWebpackDevMiddleware": true
  }
}
```

while `gulp spec-integration` gives us:

```
window.AppName = {
  config: {
    "globalNamespace": "AppName",
    "scripts": ["application.js"],
    "stylesheets": ["application.css"],
    "useRevManifest": false,
    "hotModule": false
  }
}
```

Digging further, it looks like the assets task might be using `development.json` when running `gulp` and `integration.json` when running `gulp spec-integration`

**Comment by rdy** [comment]
Can you attach a copy of your integration.js task, we think the problem might lie in that rather than anything inside of pui-react-tools.
