### ISSUE TITLE
spec-integration exits with success even when it fails

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/react-starter#3]
leading to predictable issues with `git pull -r && gulp && git push`

**Comment by rdy** [comment]
@atomanyih this is due to an error occuring from an uncaught promise. do you want uncaught promise errors to exit for webdriver specs? right now they just display an error message but do not actually throw.

**Comment by rdy** [comment]
consider the following:
beforeEach(() => {
  Promise.onPossiblyUnhandledRejection(e => expect(() => { throw e; }).not.toThrow());
});

**Comment by rdy** [comment]
Let me know if this doesn't work for you.

**Comment by atomanyih** [comment]
We moved over to capybara for integration testing, but thanks for the help!
