### ISSUE TITLE
use spy-on-render instead of providing the copy pasta

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/react-starter#7]
let's not spread more copy pasted code to teams!

instead of: https://github.com/pivotal-cf/react-starter/blob/master/spec/app/react_matchers.js

use: https://github.com/atomanyih/spy-on-render

I'll throw a PR at this when I have a spare moment

**Comment by charleshansen** [comment]
Good point. We aren't actually using the matcher in react-starter right now so I think I will delete it. We also have a larger package, [pivotal-js-jasmine-matchers](https://github.com/pivotal-cf/pivotal-js/tree/master/packages/pivotal-js-jasmine-matchers), that includes toHaveBeenRenderedWithProps that we should maybe use in the future.

**Comment by atomanyih** [comment]
ya that works too
