### ISSUE TITLE
gulp task watch-server watches for non-existent lib/, and not app/

### ISSUE THREAD

**Issue by aegatlin** [pivotal-cf/react-starter#9]
the gulp task watch-server is not watching app/ for changes. It is also watching lib/, which does not exist

**Comment by rdy** [comment]
the watch for server is for node code the runs on your server only, it restarts on changes from webpack that might get included into the package from the app but it doesn't use the watch hook.

did you have some requirement for your node server to be restarted by /app changes outside of the webpack bundle?

**Comment by charleshansen** [comment]
Talked to @aegatlin, there was a worry that the assets weren't reloading, but they are.

The server does load the app directory once when it is started up, and compiles the index.html and such. If you change files in the app directory, the server won't directly know about the changes, so you won't see any new console.logs in the server logs. The most important job of the server is to serve up the assets, which do depend on the app directory. When serving the assets, the server delegates to webpack, which is watching the app directory. By using webpack to get the assets, the server does not need to directly know about app/.
